# Generated by Django 6.0.2 on 2026-03-17 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['email'], name='user_email_7bbb4c_idx'), models.Index(fields=['username'], name='user_usernam_b79065_idx'), models.Index(fields=['is_active'], name='user_is_acti_7f3bc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='users.user')),
            ],
            options={
                'db_table': 'user_token',
                'indexes': [models.Index(fields=['token'], name='user_token_token_deff65_idx'), models.Index(fields=['user_id'], name='user_token_user_id_209416_idx')],
            },
        ),
    ]
