# Generated by Django 6.0.2 on 2026-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('uid', models.BigIntegerField(db_index=True)),
                ('status', models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Completed'), (4, 'Postponed')], default=1)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('start_time_ts', models.BigIntegerField()),
                ('end_time_ts', models.BigIntegerField()),
                ('completed_at_ts', models.BigIntegerField(blank=True, null=True)),
                ('project_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uid', 'status'], name='task_uid_5d7f66_idx'), models.Index(fields=['uid', 'start_time_ts'], name='task_uid_723078_idx'), models.Index(fields=['uid', 'end_time_ts'], name='task_uid_eafb68_idx'), models.Index(fields=['uid', 'completed_at_ts'], name='task_uid_a2635d_idx')],
            },
        ),
    ]
