# Generated by Django 6.0.2 on 2026-03-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_id',
        ),
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
