# Generated by Django 6.0.2 on 2026-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_task_description_task_due_date_task_executor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time_ts',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_ts',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='uid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
