# Generated by Django 6.0.2 on 2026-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_project_id_task_project_name'),
    ]

    operations = [
    ]
